# permissions for end users to view democrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: democrd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: democrd-viewer-role
rules:
- apiGroups:
  - demo.example.org
  resources:
  - democrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.example.org
  resources:
  - democrds/status
  verbs:
  - get
