---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.example.org
  resources:
  - democrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.example.org
  resources:
  - democrds/finalizers
  verbs:
  - update
- apiGroups:
  - demo.example.org
  resources:
  - democrds/status
  verbs:
  - get
  - patch
  - update
